<a href="https://colab.research.google.com/github/Obanai4you/CSIT-LAB-WORKS/blob/main/Dataware_Housing_And_Datamining/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LAB 4: Attribute Transformation and Dimensionality Reduction

##Objective

To apply attribute transformation and dimensionality reduction techniques on the Heart Disease dataset to improve data quality, reduce complexity, and prepare the dataset for data mining tasks.

###Definition of Attribute Transformation

Attribute transformation is the process of changing data into suitable formats for analysis or mining. It improves consistency, removes scale differences, and makes algorithms perform better.

Importance:

a. Makes data easier to analyze

b. Improves machine learning accuracy

c. Removes scale differences

d. Reduces skewness

e. Helps in feature engineering

###Definition of Dimensionality Reduction

Dimensionality reduction is the process of reducing the number of attributes while preserving important information.

Importance:

a. Reduces computation cost

b. Removes redundant features

c. Improves visualization

d. Helps reduce overfitting

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

In [6]:
heart_ds = pd.read_csv("/content/clean_heart_dataset.csv")
heart_ds.head()

The min-max normalization formula is: xxnew = (x - xmin) / (xmax - xmin)

In [3]:
heart_ds.shape

(302, 14)

In [4]:
heart_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       302 non-null    int64
 1   sex       302 non-null    int64
 2   cp        302 non-null    int64
 3   trestbps  302 non-null    int64
 4   chol      302 non-null    int64
 5   fbs       302 non-null    int64
 6   restecg   302 non-null    int64
 7   thalach   302 non-null    int64
 8   exang     302 non-null    int64
 9   oldpeak   302 non-null    float64
 10  slope     302 non-null    int64
 11  ca        302 non-null    int64
 12  thal      302 non-null    int64
 13  target    302 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.2 KB

In [5]:
heart_ds.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

##ATTRIBUTE TRANSFORMATION

##1. Normalization (Min-Max Scaling)
*************
Definition

Normalization scales data values between 0 and 1.

Formula:

xnew = (x - xmin) / (xmax - xmin)


Why for this dataset?

features like:

1. cholesterol (chol)
2. age (age)
3. blood pressure (trestbps)

have different ranges. Scaling helps compare them.

In [7]:
scaler = MinMaxScaler()

num_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

heart_ds[num_cols] = scaler.fit_transform(heart_ds[num_cols])

heart_ds.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0.479167,1,0,0.292453,0.196347,0,1,0.740458,0,0.161290,2,2,3,0
1,0.500000,1,0,0.433962,0.175799,1,0,0.641221,1,0.500000,0,0,3,0
2,0.854167,1,0,0.481132,0.109589,0,1,0.412214,1,0.419355,0,0,3,0
3,0.666667,1,0,0.509434,0.175799,0,1,0.687023,0,0.000000,2,1,3,0
4,0.687500,0,0,0.415094,0.383562,1,1,0.267176,0,0.306452,1,3,2,0

##2. Standardization (Z-score)
***************
###Definition:

Transforms data to mean = 0 and standard deviation = 1.

Formula
Z=
(x−μ)/σ
	​

Why?

Useful when values vary a lot.

In [8]:
std = StandardScaler()

heart_std = pd.DataFrame(
    std.fit_transform(heart_ds[num_cols]),
    columns=num_cols
)

heart_std.head()

        age  trestbps      chol   thalach   oldpeak
0 -0.267966 -0.376556 -0.667728  0.806035 -0.037124
1 -0.157260  0.478910 -0.841918  0.237495  1.773958
2  1.724733  0.764066 -1.403197 -1.074521  1.342748
3  0.728383  0.935159 -0.841918  0.499898 -0.899544
4  0.839089  0.364848  0.919336 -1.905464  0.739054

###3. Log Transformation
*************************
###Definition

Log transformation reduces skewness.

Cholesterol and blood pressure can be right-skewed.

In [9]:
log_df = heart_ds.copy()

log_df['chol'] = np.log1p(log_df['chol'])
log_df['trestbps'] = np.log1p(log_df['trestbps'])

log_df[['chol','trestbps']].head()

       chol  trestbps
0  0.179273  0.256542
1  0.161948  0.360441
2  0.103990  0.392807
3  0.161948  0.411735
4  0.324661  0.347196

##4. Binning
*********************
###Definition:

Binning converts continuous values into categories.

Age can be grouped into patient age groups.

In [10]:
heart_ds['age_group'] = pd.cut(
    heart_ds['age'],
    bins=3,
    labels=['Young','Middle','Old']
)

heart_ds[['age','age_group']].head()

        age age_group
0  0.479167    Middle
1  0.500000    Middle
2  0.854167       Old
3  0.666667    Middle
4  0.687500       Old

##DIMENSIONALITY REDUCTION:

Dimensionality reduction is all about summarizing the data with most of the information preserved in compact form.Reducing the dimension of the feature space, creates fewer relationships between variables. PCA reduces features while keeping maximum information.

It is needed for:

a. Reduce number of attributes

b. Remove redundant features

c. Improve efficiency of analysis

###Step 1: Separate Features and Target:

Before applying dimensionality reduction, we separate:

i. Independent variables (X)

ii. Dependent variable (y)

In [11]:
X = heart_ds.drop('target', axis=1)
y = heart_ds['target']

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,age_group
0,0.479167,1,0,0.292453,0.196347,0,1,0.740458,0,0.161290,2,2,3,Middle
1,0.500000,1,0,0.433962,0.175799,1,0,0.641221,1,0.500000,0,0,3,Middle
2,0.854167,1,0,0.481132,0.109589,0,1,0.412214,1,0.419355,0,0,3,Old
3,0.666667,1,0,0.509434,0.175799,0,1,0.687023,0,0.000000,2,1,3,Middle
4,0.687500,0,0,0.415094,0.383562,1,1,0.267176,0,0.306452,1,3,2,Old

###Step 2: Select Numerical Features

PCA works only on numerical data, so we select only numeric columns.

In [12]:
X = X.select_dtypes(include=['int64', 'float64'])
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,0.479167,1,0,0.292453,0.196347,0,1,0.740458,0,0.161290,2,2,3
1,0.500000,1,0,0.433962,0.175799,1,0,0.641221,1,0.500000,0,0,3
2,0.854167,1,0,0.481132,0.109589,0,1,0.412214,1,0.419355,0,0,3
3,0.666667,1,0,0.509434,0.175799,0,1,0.687023,0,0.000000,2,1,3
4,0.687500,0,0,0.415094,0.383562,1,1,0.267176,0,0.306452,1,3,2

###Step 3: Feature Scaling (Standardization)

Scaling is necessary because:

a. Features have different ranges

b. PCA is sensitive to scale

We use Z-score standardization.

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

###Step 4: Apply PCA

PCA converts original features into new features called:
Principal Components (PC1, PC2, etc.)

We reduce dataset into 2 components for simplicity.

In [16]:
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

###Step 5: Create PCA DataFrame

Store transformed data into a new dataset.

In [18]:
pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
pca_df.head()

        PC1       PC2
0 -0.403727 -1.152038
1  2.614955 -0.600532
2  3.110398 -1.303946
3 -0.392439 -0.322416
4  2.255588  1.971414

###Step 6: Check Explained Variance

Explained variance shows how much information is retained by each component.

In [19]:
pca.explained_variance_ratio_

array([0.21313479, 0.11859478])

In [22]:
print(pca.components_)

[[ 0.3132666   0.09392164 -0.2725298   0.18487583  0.11382658  0.07401622
  -0.12540304 -0.41448147  0.35853249  0.4176868  -0.37637662  0.29165252
   0.22114956]
 [ 0.40784766 -0.3710019   0.2989378   0.43718082  0.3621942   0.31840408
  -0.21861133  0.08082548 -0.26608056 -0.0559463   0.05526682  0.11117111
  -0.19823027]]

#Conclusion
********************
Dimensionality reduction was successfully performed using PCA. The original dataset with multiple features was reduced to two principal components while preserving most of the variance. This reduces complexity and improves efficiency for further analysis.